# MySQL databse
default: &default
  adapter: mysql2
  database: timerapp
  username: root
  password: root
  host: localhost

development:
  <<: *default
  socket: /tmp/mysql.sock

test:
  <<: *default

staging:
  <<: *default
  socket: /var/run/mysqld/mysqld.sock

production:
  <<: *default
  socket: /var/run/mysqld/mysqld.sock