# MySQL databse
default: &default
  adapter: mysql2
  database: timerapp
  username: root
  password: root
  host: localhost
  socket: /var/run/mysqld/mysql.sock

development:
  <<: *default
  socket: /tmp/mysql.sock
test:
  <<: *default

staging:
  <<: *default
  socket: /tmp/mysql.sock
production:
  <<: *default
  socket: /tmp/mysql.sock